app/recipe/__init__.py
#!/usr/bin/env python3
# coding:utf-8
from flask import Blueprint

recipe = Blueprint('recipe', __name__, static_folder='../static')

from . import views

app/recipe/views.py
#!/usr/bin/env python3.5
# coding:utf-8
from flask import render_template
from flask import redirect
from flask import url_for
from flask import request
from werkzeug.utils import secure_filename
from flask_login import login_required, current_user
from . import recipe
from ..models import Material, Recipe, Step, Questions, User
from ..log import Log
import os

uploads_dir = './app/static/images/'  # 以.app为起点，用于删除或重命名图片文件
static_images_dir = 'static/images/'  # 保存到数据库中的图片路径，供template调用
allow_extensions = set(['png', 'jpg', 'jpeg'])  # 允许的图片格式


def allowed_file(filename):  # 允许的文件格式
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in allow_extensions


def upload(f, file_formate, uploads_dir, static_images_dir):
    '''
    file_formate 是对上传图片文件名rename的格式，reicpe的图片因为要引用recipe_id作为
    文件名的一部分，在此为Null，在Model的add方法中对其rename格式
    '''

    if allowed_file(f.filename):
        filename = secure_filename(f.filename)
        path = uploads_dir + filename
        f.save(path)
        if file_formate:
            os.rename(uploads_dir + filename, uploads_dir + file_formate + filename)  # 按给定格式修改上传的文件
            filename = static_images_dir + file_formate + filename
            return filename
        else:
            return filename


def material_add(form, recipe_id):
    dic = {}
    for i in range(1, 11):  # 暂定用十种材料
        material_name = form.get('material' + str(i))
        amount_value = form.get('amount' + str(i))
        if material_name:
            dic[i] = {material_name: amount_value}
    for i, values in dic.items():
        for k, v in values.items():
            material = Material(i, k, v, recipe_id)
            material.add()


def material_update(form, recipe_id):
    material_names = Material.query.with_entities(Material.name).filter_by(
        recipe_id=recipe_id).all()  # 返回的是[('酱油',), ('辣椒',)]的格式
    materials = []
    for m in material_names:  # 转化成['酱油', '辣椒']的格式
        materials.append(''.join(m))
    for i in range(1, 11):
        material_name = form.get('material' + str(i))
        amount_value = form.get('amount' + str(i))
        if (material_name) or (amount_value):
            material = Material.query.filter_by(recipe_id=recipe_id, material_number=i).first()
            if material:
                material.update(material_name, amount_value)
            else:
                m = Material(i, material_name, amount_value, recipe_id)
                m.add()


def steps_add(form, recipe_id):
    for i in range(1, 11):  # 暂定只用十步
        technique = form.get('step' + str(i) + '_introduce')
        f = request.files.get('step' + str(i) + '_pictures')
        file_formate = 'recipe_' + str(recipe_id) + '_step_' + str(i) + '_'
        if technique:
            filename = upload(f, file_formate, uploads_dir, static_images_dir)
            steps = Step(i, technique, filename, recipe_id)
            steps.add()


def steps_update(form, recipe_id):
    steps = Step.query.with_entities(Step.step_number).filter_by(recipe_id=recipe_id).all()  # 返回如[(1,), （2,), (3,)]的格式
    step_numbers = [s[0] for s in steps]  # 转换成[1, 2, 3]的格式
    for i in range(1, 11):
        technique = form.get('step' + str(i) + '_introduce')
        f = request.files.get('step' + str(i) + '_pictures')
        file_formate = 'recipe_' + str(recipe_id) + '_step_' + str(i) + '_'
        if technique or f:
            filename = upload(f, file_formate, uploads_dir, static_images_dir)
            s = Step.query.filter_by(recipe_id=recipe_id, step_number=i).first()
            if s:
                if s.pictures:  # 如果已经配有图片
                    os.remove('app/' + s.pictures)  # 删掉旧图片
                    s.update(i, technique, filename)
                else:  # 只有做法没有图片，对step做update
                    s.update(i, technique, filename)
            else: #新增的做法或图片
                steps = Step(i, technique, filename, recipe_id)
                steps.add()


@recipe.route('/', methods=['GET'])
@login_required
def index():
    return render_template('recipe.html')


@recipe.route('/recipe_add', methods=['POST'])
@login_required
def recipe_add():
    form = request.form
    f = request.files.get('pictures')
    tips = form.get('tips')
    if f:
        filename = upload(f, None, uploads_dir, static_images_dir)
        recipe = Recipe(form, filename, tips)
        recipe.add()
        recipe_id = recipe.id
        material_add(form, recipe_id)
        steps_add(form, recipe_id)
    else:
        return redirect(url_for('recipe.index'))
    return redirect(url_for('main.index'))


@recipe.route('/recipe_information', methods=['GET'])
def recipe_information():
    recipe_id = int(request.args.get('recipe_id'))
    recipes = Recipe.query.filter_by(id=recipe_id).first()
    return render_template('recipe_information.html', recipes=recipes)


@recipe.route('/recipe_edit', methods=['GET'])
@login_required
def recipe_edit():
    recipe_id = int(request.args.get('recipe_id'))
    recipes = Recipe.query.filter_by(id=recipe_id).first()
    material_length = len(recipes.materials.all())
    step_length = len(recipes.steps.all())
    return render_template('recipe_edit.html', recipes=recipes, material_length=material_length,
                           step_length=step_length)


@recipe.route('/recipe_update', methods=['POST'])
@login_required
def recipe_update():
    recipe_id = int(request.args.get('recipe_id'))
    recipe_item = Recipe.query.filter_by(id=recipe_id).first()
    form = request.form
    f = request.files.get('pictures')
    file_formate = 'recipe_' + str(recipe_id) + '_'
    if f:
        os.remove('app/' + recipe_item.pictures)  # 如果有图片更新，先删除旧图片
        filename = upload(f, file_formate, uploads_dir, static_images_dir)
    else:
        filename = ''
    recipes = Recipe.query.filter_by(id=recipe_id).first()
    recipes.update(form, filename)
    material_update(form, recipe_id)
    steps_update(form, recipe_id)
    return redirect(url_for('recipe.recipe_information', recipe_id=recipe_id))


@recipe.route('/recipe_delete', methods=['GET'])
@login_required
def recipe_delete():
    recipe_id = int(request.args.get('recipe_id'))
    recipes = Recipe.query.filter_by(id=recipe_id).all()
    materials = Material.query.filter_by(recipe_id=recipe_id)
    steps = Step.query.filter_by(recipe_id=recipe_id)
    if current_user.name == recipes[0].author or current_user.name == 'admin':
        for m in materials:
            m.delete_element()
        for s in steps:
            s.delete_element()
        for r in recipes:
            r.delete_element()
    return redirect(url_for('main.index'))


@recipe.route('/recipe_questions', methods=['GET'])
def recipe_questions():
    recipe_id = request.args.get('recipe_id')
    recipes = Recipe.query.filter_by(id=int(recipe_id)).first()
    questionsList = User.query.join(Questions, User.name == Questions.author).add_columns(User.picture, User.name,
                                                                                          Questions.content).filter(
        User.name == Questions.author).filter(Questions.recipe_id == int(recipe_id)).all()
    return render_template('recipe_questions.html', recipe_id=recipe_id, questionsList=questionsList, recipes=recipes)


@recipe.route('/recipe_questions_view', methods=['GET'])
@login_required
def recipe_questions_view():
    recipe_id = request.args.get('recipe_id')
    return render_template('recipe_questions_add.html', recipe_id=recipe_id)


@recipe.route('/recipe_questions_add', methods=['POST'])
@login_required
def recipe_questions_add():
    form = request.form
    content = form.get('contents')
    recipe_id = request.args.get('recipe_id')
    author = current_user.name
    question = Questions(content, recipe_id, author)
    question.add()
    return redirect(url_for('recipe.recipe_questions', recipe_id=recipe_id))

app/templates/recipe.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en" xmlns:margin="http://www.w3.org/1999/xhtml">
<head>
    {% block head %}
    {{ super() }}
    {% endblock %}
</head>
<body>
{% block body %}
{{ super() }}

<div class="container">
    <form class="form-inline" role="form" enctype="multipart/form-data" action={{url_for("recipe.recipe_add")}}
          method="post">
        <input type="hidden" name="_csrf_token" value="{{ csrf_token() }}">
        <div class="col-md-6">
            <input name="name" type="text" class="form-control" placeholder="菜谱名称">
        </div>
        <div class="col-md-12"></div>
        <br>
        <div class="col-md-12"></div>
        <br>
        <div class="col-md-6">
            <span
                style="color:#922;font-size: 12px;font-family: CustomFont,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif ">*菜谱封面(仅支持png jpg jpeg格式,必填）：</span>
            <input name="pictures" type="file" class="form-control" style="padding-top: 30px;padding-bottom: 60px;"
                   value="菜谱封面">
        </div>
        <div class="col-md-12"></div>
        <div class="col-md-12">
            <h5>简介：</h5>
            <textarea name="introduce" class="form-control" placeholder="菜谱描述" rows="5" cols="58"
                      style="resize:none"></textarea>
        </div>
        <div class="col-md-12">
            <h5>用料：</h5>
            <div class="col-md-5">
                <table>
                    <tr>
                        <th><input type="text" name="material1" placeholder="用料名称"></th>
                        <th><input type="text" name="amount1" placeholder="用量"></th>
                    </tr>
                    <div class="col-md-12"></div>
                    <tr>
                        <th><input type="text" name="material2" placeholder="用料名称"></th>
                        <th><input type="text" name="amount2" placeholder="用量"></th>
                    </tr>
                    <div class="col-md-12"></div>
                    <tr>
                        <th><input type="text" name="material3" placeholder="用料名称"></th>
                        <th><input type="text" name="amount3" placeholder="用量"></th>
                    </tr>
                    <div class="col-md-12"></div>
                    <tr>
                        <th><input type="text" name="material4" placeholder="用料名称"></th>
                        <th><input type="text" name="amount4" placeholder="用量"></th>
                    </tr>
                    <div class="col-md-12"></div>
                    <tr>
                        <th><input type="text" name="material5" placeholder="用料名称"></th>
                        <th><input type="text" name="amount5" placeholder="用量"></th>
                    </tr>
                    <div class="col-md-12"></div>
                    <tr>
                        <th><input type="text" name="material6" placeholder="用料名称"></th>
                        <th><input type="text" name="amount6" placeholder="用量"></th>
                    </tr>
                    <div class="col-md-12"></div>
                    <tr>
                        <th><input type="text" name="material7" placeholder="用料名称"></th>
                        <th><input type="text" name="amount7" placeholder="用量"></th>
                    </tr>
                    <div class="col-md-12"></div>
                    <tr>
                        <th><input type="text" name="material8" placeholder="用料名称"></th>
                        <th><input type="text" name="amount8" placeholder="用量"></th>
                    </tr>
                    <div class="col-md-12"></div>
                    <tr>
                        <th><input type="text" name="material9" placeholder="用料名称"></th>
                        <th><input type="text" name="amount9" placeholder="用量"></th>
                    </tr>
                    <div class="col-md-12"></div>
                    <tr>
                        <th><input type="text" name="material10" placeholder="用料名称"></th>
                        <th><input type="text" name="amount10" placeholder="用量"></th>
                    </tr>
                </table>
            </div>
            <div class="col-md-7"></div>
        </div>
        <div class="col-md-12"></div>
        <div class="col-md-12"></div>
        <div class="col-md-12">
            <h5>做法（每一步骤和对应图片）：</h5>
            <div class="form-group">
                <textarea name="step1_introduce" class="form-control" placeholder="菜谱步骤1" style="resize:none" rows="3"
                          cols="28"></textarea>
            </div>
            <div class="form-group">
                <input name="step1_pictures" type="file" class="form-control"
                       style="padding-top: 30px;padding-bottom: 60px;" placeholder="封面">
            </div>
        </div>
        <div class="col-md-12"></div>
        <div class="col-md-12">
            <div class="form-group">
                <textarea name="step2_introduce" class="form-control" placeholder="菜谱步骤2" style="resize:none" rows="3"
                          cols="28"></textarea>
            </div>
            <div class="form-group">
                <input name="step2_pictures" type="file" class="form-control"
                       style="padding-top: 30px;padding-bottom: 60px;" placeholder="封面">
            </div>
        </div>
        <div class="col-md-12"></div>
        <div class="col-md-12">
            <div class="form-group">
                <textarea name="step3_introduce" class="form-control" placeholder="菜谱步骤3" style="resize:none" rows="3"
                          cols="28"></textarea>
            </div>
            <div class="form-group">
                <input name="step3_pictures" type="file" class="form-control"
                       style="padding-top: 30px;padding-bottom: 60px;" placeholder="封面">
            </div>
        </div>
        <div class="col-md-12"></div>
        <div class="col-md-12">
            <div class="form-group">
                <textarea name="step4_introduce" class="form-control" placeholder="菜谱步骤4" style="resize:none" rows="3"
                          cols="28"></textarea>
            </div>
            <div class="form-group">
                <input name="step4_pictures" type="file" class="form-control"
                       style="padding-top: 30px;padding-bottom: 60px;" placeholder="封面">
            </div>
        </div>
        <div class="col-md-12"></div>
        <div class="col-md-12">
            <div class="form-group">
                <textarea name="step5_introduce" class="form-control" placeholder="菜谱步骤5" style="resize:none" rows="3"
                          cols="28"></textarea>
            </div>
            <div class="form-group">
                <input name="step5_pictures" type="file" class="form-control"
                       style="padding-top: 30px;padding-bottom: 60px;" placeholder="封面">
            </div>
        </div>
        <div class="col-md-12"></div>
        <div class="col-md-12">
            <div class="form-group">
                <textarea name="step6_introduce" class="form-control" placeholder="菜谱步骤6" style="resize:none" rows="3"
                          cols="28"></textarea>
            </div>
            <div class="form-group">
                <input name="step6_pictures" type="file" class="form-control"
                       style="padding-top: 30px;padding-bottom: 60px;" placeholder="封面">
            </div>
        </div>
        <div class="col-md-12"></div>
        <div class="col-md-12">
            <div class="form-group">
                <textarea name="step7_introduce" class="form-control" placeholder="菜谱步骤7" style="resize:none" rows="3"
                          cols="28"></textarea>
            </div>
            <div class="form-group">
                <input name="step7_pictures" type="file" class="form-control"
                       style="padding-top: 30px;padding-bottom: 60px;" placeholder="封面">
            </div>
        </div>
        <div class="col-md-12"></div>
        <div class="col-md-12">
            <div class="form-group">
                <textarea name="step8_introduce" class="form-control" placeholder="菜谱步骤8" style="resize:none" rows="3"
                          cols="28"></textarea>
            </div>
            <div class="form-group">
                <input name="step8_pictures" type="file" class="form-control"
                       style="padding-top: 30px;padding-bottom: 60px;" placeholder="封面">
            </div>
        </div>
        <div class="col-md-12"></div>
        <div class="col-md-12">
            <div class="form-group">
                <textarea name="step9_introduce" class="form-control" placeholder="菜谱步骤9" style="resize:none" rows="3"
                          cols="28"></textarea>
            </div>
            <div class="form-group">
                <input name="step9_pictures" type="file" class="form-control"
                       style="padding-top: 30px;padding-bottom: 60px;" placeholder="封面">
            </div>
        </div>
        <div class="col-md-12"></div>
        <div class="col-md-12">
            <div class="form-group">
                <textarea name="step10_introduce" class="form-control" placeholder="菜谱步骤10" style="resize:none" rows="3"
                          cols="28"></textarea>
            </div>
            <div class="form-group">
                <input name="step10_pictures" type="file" class="form-control"
                       style="padding-top: 30px;padding-bottom: 60px;" placeholder="封面">
            </div>
        </div>
        <div class="col-md-12"></div>
        <div class="col-md-12">
            <h5>小贴士：</h5>
            <textarea name="tips" class="form-control" placeholder="添加小贴士" style="resize:none" rows="5"
                      cols="58"></textarea>
        </div>
        <div class="col-md-12"></div>
        <div class="col-md-6">
            <input type="submit" value="发布菜谱">
        </div>
    </form>
</div>
{% endblock %}

{% block footer %}
{{ super() }}
{% endblock %}

</body>

<div class="col-md-12">
    <form class="form-inline" role="form">
        <input type="text" class="span2" placeholder="用料名称">
        <input type="text" class="span3" placeholder="用量">
    </form>
</div>
</html>

app/templates/recipe_edit.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en" xmlns:margin="http://www.w3.org/1999/xhtml">
<head>
    {% block head %}
    {{ super() }}
    {% endblock %}
</head>
<body>
{% block body %}
{{ super() }}

<div class="container">
    <form class="form-inline" role="form" enctype="multipart/form-data" action={{url_for("recipe.recipe_update",
          recipe_id=recipes.id)}} method="post">
        <input type="hidden" name="_csrf_token" value="{{ csrf_token() }}">
        <div class="col-md-6">
            <p>菜谱名称：</p>
            <input name="name" type="text" class="form-control" placeholder="{{recipes.name}}">
        </div>
        <div class="col-md-12"></div>
        <br>
        <div class="col-md-6">
            <h5>菜谱封面：</h5>
            <input name="pictures" type="file" class="form-control" style="padding-top: 30px;padding-bottom: 60px;"
                   placeholder="封面">
        </div>
        <div class="col-md-12"></div>
        <div class="col-md-12">
            <h5>简介：</h5>
            <textarea name="introduce" class="form-control" placeholder="{{recipes.introduce}}" style="resize:none"
                      rows="9" cols="58"></textarea>
        </div>
        <div class="col-md-12">
            <h5>用料：</h5>
            {% if material_length==0 %}
            {% for i in range(1, 11) %}
            <div class="col-md-7">
                <table>
                    <tr>
                        <th><input type="text" name="material{{i}}" placeholder="用料名称"></th>
                        <th><input type="text" name="amount{{i}}" placeholder="用量"></th>
                    </tr>
                </table>
            </div>
            {% endfor %}
            <div class="col-md-5"></div>
            {% elif material_length==10 %}
            {% set i=1 %}
            {% for material in recipes.materials.all() %}
            <div class="col-md-7">
                <table>
                    <tr>
                        <th><input type="text" name="material{{i}}" placeholder="{{material.name}}"></th>
                        <th><input type="text" name="amount{{i}}" placeholder="{{material.amount}}"></th>
                    </tr>
                </table>
            </div>
            {% set i=i+1 %}
            {% endfor %}
            <div class="col-md-5"></div>
            {% else %}
            {% set i=1 %}
            {% for material in recipes.materials.all() %}
            <div class="col-md-7">
                <table>
                    <tr>
                        <th><input type="text" name="material{{i}}" placeholder="{{material.name}}"></th>
                        <th><input type="text" name="amount{{i}}" placeholder="{{material.amount}}"></th>
                    </tr>
                </table>
            </div>
            {% set i=i+1 %}
            <div class="col-md-5"></div>
            {% endfor %}
            {% for j in range(material_length+1, 11) %}
            <div class="col-md-7">
                <table>
                    <tr>
                        <th><input type="text" name="material{{j}}" placeholder="用料名称{{j}}"></th>
                        <th><input type="text" name="amount{{j}}" placeholder="用量"></th>
                    </tr>
                </table>
            </div>
            {% endfor %}
            <div class="col-md-5"></div>
            {% endif %}
        </div>
        <div class="col-md-12"></div>
        <div class="col-md-12">
            <h5>做法：</h5>
            {% if step_length==0 %}
            {% for i in range(1, 11) %}
            <div class="form-group">
                <textarea name="step{{i}}_introduce" class="form-control" placeholder="菜谱步骤" style="resize:none"
                          rows="3" cols="28"></textarea>
            </div>
            <div class="form-group">
                <input name="step{{i}}_pictures" type="file" class="form-control"
                       style="padding-top: 30px;padding-bottom: 60px;" placeholder="封面">
            </div>
            {% endfor %}
            {% elif step_length==10 %}
            {% for step in recipes.steps.all() %}
            <div class="form-group">
                <textarea name="step{{i}}_introduce" class="form-control"
                          placeholder="菜谱步骤{{step.step_number}}: {{step.technique}}" style="resize:none" rows="3"
                          cols="28"></textarea>
            </div>
            <div class="form-group">
                <input name="step{{i}}_pictures" type="file" class="form-control"
                       style="padding-top: 30px;padding-bottom: 60px;" placeholder="封面">
            </div>
            {% endfor %}
            {% else %}
            {% set i=1 %}
            {% for step in recipes.steps.all() %}
            <div class="form-group">
                <textarea name="step{{i}}_introduce" class="form-control"
                          placeholder="菜谱步骤{{step.step_number}}: {{step.technique}}" style="resize:none" rows="3"
                          cols="28"></textarea>
            </div>
            <div class="form-group">
                <input name="step{{i}}_pictures" type="file" class="form-control"
                       style="padding-top: 30px;padding-bottom: 60px;" placeholder="封面">
            </div>
            {% set i=i+1 %}
            {% endfor %}
            {% for j in range(step_length+1, 11) %}
            <div class="form-group">
                <textarea name="step{{j}}_introduce" class="form-control" placeholder="菜谱步骤" style="resize:none"
                          rows="3" cols="28"></textarea>
            </div>
            <div class="form-group">
                <input name="step{{j}}_pictures" type="file" class="form-control"
                       style="padding-top: 30px;padding-bottom: 60px;" placeholder="封面">
            </div>
            {% endfor %}
            {% endif %}
        </div>

        <div class="col-md-12"></div>
        <div class="col-md-12"></div>
        <div class="col-md-12">
            <h5>小贴士：</h5>
            <textarea name="tips" class="form-control" placeholder="{{recipes.tips}}" style="resize:none" rows="9"
                      cols="58"></textarea>
        </div>
        <div class="col-md-12"></div>
        <div class="col-md-6">
            <input type="submit" value="提交修改">
        </div>
    </form>
</div>
{% endblock %}

{% block footer %}
{{ super() }}
{% endblock %}

</body>
</html>

app/templates/recipe_information.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    {{ super() }}
    {% endblock %}
</head>
<body>
{% block body %}
{{ super() }}

<div class="container">
    <div class="col-md-8">
        <p style="color:#000;font-size:28px;font-family:CustomFont,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif">
            {{recipes.name}}</p>
    </div>
    <div class="col-md-4">
        <p>
            {% if current_user.name==recipes.author or current_user.name=='admin' %}
            <a href={{url_for("recipe.recipe_edit", recipe_id=recipes.id)}}
               style="color:rgb(178, 68, 34);font-size:14px;font-family:CustomFont,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif">修改菜谱</a>
            <a href={{url_for("recipe.recipe_delete", recipe_id=recipes.id)}}
               style="color:rgb(178, 68, 34);font-size:14px;font-family:CustomFont,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif">|
                删除菜谱</a>
            {% endif %}
            {% if current_user.is_authenticated %}
            <a href={{url_for("recipe.index")}}
               style="color:rgb(178, 68, 34);font-size:14px;font-family:CustomFont,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif">|
                创建菜谱</a>
            {% endif %}
        </p>
    </div>
    <div class="col-md-9">
        <img class="featurette-image img-responsive" src="{{ recipes.pictures }}" data-src="holder.js/300x300/auto"
             alt="Generic placeholder image">
        <br>
    </div>
    <div class="com-md-12">
        <div class="col-md-9">
            <p style="color:rgb(200,190,172);font-size:20px;font-family:CustomFont,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif">
                简介：</p>
            {% if recipes.introduce %}
            <textarea name="introduce" class="form-control" placeholder="菜谱描述" rows="11" cols="58" boder-color=rgb(255,
                      255, 255) style="resize:none">{{ recipes.introduce }}</textarea>
            {% else %}
            <textarea name="introduce" class="form-control" placeholder="菜谱描述" rows="3" cols="58" boder-color=rgb(255,
                      255, 255) style="resize:none">暂无该菜谱描述</textarea>
            {% endif %}
        </div>
    </div>
    <div class="com-md-12">
        <div class="col-md-6">
            <p style="color:rgb(200,190,172);font-size:20px;font-family:CustomFont,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif">
                <br>用料：</p>
            <table class="table table-table-condensed">
                {% if recipes.materials.all() %}
                <tr>
                    <th>用料名称：</th>
                    <th>用量：</th>
                </tr>
                {% for material in recipes.materials.all() %}
                <tr>
                    <th>{{ material.name }}</th>
                    <th> {{ material.amount }}</th>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <th>暂无该菜谱用料信息</th>
                </tr>
                {% endif %}
            </table>
        </div>
        <div class="col-md-6"></div>
    </div>
    <div class="col-md-12">
        <p style="color:rgb(200,190,172);font-size:20px;font-family:CustomFont,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif">
            {{ recipes.name }}的做法:</p>
        {% if recipes.steps.all() %}
        {% for step in recipes.steps.all() %}
        <div class="col-md-6">
            <p style="color:rgb(0,0,0);font-size:15px;font-family:CustomFont,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif">
                {{ step.step_number }}:{{ step.technique }}</p>
        </div>
        <div class="col-md-3">
            {% if (step.pictures) %}
            <img class="featurette-image img-responsive" data-src="holder.js/200x200/auto"
                 alt="Generic placeholder image" src={{step.pictures}}>
            {% endif %}
        </div>
        <div class="col-md-3"></div>
        <div class="col-md-12"></div>
        <div class="col-md-12"></div>
        {% endfor %}
        {% else %}
        <div class="col-md-12">
            <p style="color:rgb(0,0,0);font-size:15px;font-family:CustomFont,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif">
                暂无该菜谱做法信息</p>
        </div>
        <br><br>
        {% endif %}
    </div>
    <div class="com-md-12">
        <div class="col-md-9">
            <p style="color:rgb(200,190,172);font-size:20px;font-family:CustomFont,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif">
                小贴士：</p>
            {% if recipes.tips %}
            <textarea name="introduce" class="form-control" rows="11" cols="58" boder-color=rgb(255, 255, 255)
                      style="resize:none">{{ recipes.tips }}</textarea>
            {% else %}
            <textarea name="introduce" class="form-control" rows="3" cols="58" boder-color=rgb(255, 255, 255)
                      style="resize:none">暂无该菜谱贴士</textarea>
            {% endif %}
        </div>
    </div>
    <div class="com-md-12">
        <div class="col-md-9">
            <br>
            <p style="color:rgb(200,190,172);font-size:20px;font-family:CustomFont,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif">
                {{recipes.name}}的留言：</p>
            <p><a href={{url_for("recipe.recipe_questions", recipe_id=recipes.id)}}
                  style="color:rgb(178, 68, 34);font-size:14px;font-family:CustomFont,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif">查看菜谱留言</a>
            </p>
        </div>
    </div>
    <div class="col-md-12">
        <div class="col-md-12"><br></div>
        <div class="col-md-8"></div>
        <div class="col-md-4">
            <p>
                {% if current_user.name == recipes.author or current_user.name == 'admin' %}
                <a href={{url_for("recipe.recipe_edit", recipe_id=recipes.id)}}
                   style="color:rgb(178, 68, 34);font-size:14px;font-family:CustomFont,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif">修改菜谱</a>
                <a href={{url_for("recipe.recipe_delete", recipe_id=recipes.id)}}
                   style="color:rgb(178, 68, 34);font-size:14px;font-family:CustomFont,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif">|
                    删除菜谱</a>
                {% endif %}
                {% if current_user.is_authenticated %}
                <a href={{url_for("recipe.index")}}
                   style="color:rgb(178, 68, 34);font-size:14px;font-family:CustomFont,Microsoft YaHei,WenQuanYi Micro Hei,sans-serif">|
                    创建菜谱</a>
                {% endif %}
            </p>
        </div>
    </div>
</div>
{% endblock %}

{% block footer %}
{{ super() }}
{% endblock %}
</body>
</html>